apiVersion: apps/v1
kind: Deployment
metadata:
  name: myclient
  namespace: ibac-for-kafka
spec:
  selector:
    matchLabels:
      app: myclient
  template:
    metadata:
      labels:
        app: myclient
      annotations:
        spire-integration.otterize.com/tls-secret-name: myclient-credentials-secret
    spec:
      containers:
        - name: myclient
          image: golang
          command: [ "/bin/sh", "-c", "--" ]
          args: [ "sleep infinity" ]
